import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Topic, { PropstTopic } from '../components/topic'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const topic1: PropstTopic = {
    href: 'https://nextjs.org/docs',
    title: <>Documentation &rarr;</>,
    content: 'Find in-depth information about Next.js features and API.'
  }

  const topic2: PropstTopic = {
    href: 'https://nextjs.org/learn',
    title: <>Learn &rarr;</>,
    content:'Learn about Next.js in an interactive course with quizzes!' 
  }

  const topic3: PropstTopic = {
    href: 'https://github.com/vercel/next.js/tree/canary/examples',
    title: <>Examples &rarr;</>,
    content: 'Discover and deploy boilerplate example Next.js projects.'
  }

  const topic4: PropstTopic = {
    href: 'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
    title: <>Deploy &rarr;</>,
    content: 'Instantly deploy your Next.js site to a public URL with Vercel.'
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          
          <Topic {...topic1} />

          <Topic {...topic2} />

          <Topic {...topic3} />

          <Topic {...topic4} />
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
